name: One-Time Key Generator
on: workflow_dispatch # يتم تشغيله يدوياً فقط
jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Generate Permanent Key
        run: |
          keytool -genkey -v -keystore mihrab.jks -keyalg RSA -keysize 2048 -validity 10000 -alias mihrab-key -storepass password123 -keypass password123 -dname "CN=Mihrab, O=Dev, C=US"
          echo "COPY THIS CODE BELOW:"
          base64 -w 0 mihrab.jks
